package db

import . "github.com/kaulie/autonomy/src"

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"
)

// ExecutionStore, as the postgres engine serves it: the execution plan/step tables.
// Every method here inserts or reads: a plan is written before its steps run and never
// rewritten, its outcome is derived from the steps, and nothing is keyed on the cycle
// (see docs/execution-step.md).

// pgExecutionDDL creates the planner's four tables and the indexes that read them.
// A plan's outcome is derived (the status of its last execution step); a planned step
// with no execution row simply never ran.
const pgExecutionDDL = `
CREATE TABLE IF NOT EXISTS execution_plan (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id               TEXT NOT NULL DEFAULT '',
  agent_id              BIGINT NOT NULL DEFAULT 0,
  cycle                 INTEGER NOT NULL DEFAULT 0, -- this agent's own round (ordering only)
  decision_type         TEXT NOT NULL DEFAULT '',   -- plan | done | blocked | need_input
  reason                TEXT NOT NULL DEFAULT '',
  evidence              TEXT NOT NULL DEFAULT '[]',
  need                  TEXT NOT NULL DEFAULT '',   -- what blocked / need_input asked for
  step_count            INTEGER NOT NULL DEFAULT 0,
  plan_hash             TEXT NOT NULL DEFAULT '',   -- the planned steps' fingerprint
  reply_message_id      BIGINT,                     -- llm_messages: the planner reply this plan is
  input_message_id      BIGINT,                     -- llm_messages: the input that reply answered
  task_input_message_id BIGINT,                     -- llm_messages: the task's own first user input
  reason_turn_id        BIGINT,                     -- reason_turns: the run that produced the reply
  created_at            TIMESTAMPTZ NOT NULL,
  UNIQUE(reply_message_id)
);
CREATE INDEX IF NOT EXISTS idx_execution_plan_task ON execution_plan(task_id, id);

CREATE TABLE IF NOT EXISTS execution_step_plan (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id         BIGINT NOT NULL, -- execution_plan.id
  idx             INTEGER NOT NULL, -- position in the plan (1-based)
  name            TEXT NOT NULL DEFAULT '', -- a binding addresses it as step:<name>.output.<key>
  capability      TEXT NOT NULL DEFAULT '',
  input           TEXT NOT NULL DEFAULT '{}', -- the input the plan asked for, verbatim
  expected_effect TEXT NOT NULL DEFAULT '',
  evidence_refs   TEXT NOT NULL DEFAULT '[]',
  created_at      TIMESTAMPTZ NOT NULL,
  UNIQUE(plan_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_execution_step_plan_plan ON execution_step_plan(plan_id);

CREATE TABLE IF NOT EXISTS execution_step (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id      BIGINT NOT NULL, -- execution_plan.id
  plan_step_id BIGINT NOT NULL, -- execution_step_plan.id
  task_id      TEXT NOT NULL DEFAULT '',
  agent_id     BIGINT NOT NULL DEFAULT 0,
  cycle        INTEGER NOT NULL DEFAULT 0,
  idx          INTEGER NOT NULL DEFAULT 0, -- execution order within the plan
  name         TEXT NOT NULL DEFAULT '', -- what the plan called this step
  capability   TEXT NOT NULL DEFAULT '',
  provider     TEXT NOT NULL DEFAULT '', -- github / agent-control-plane / cursor / cline / autonomy
  status       TEXT NOT NULL DEFAULT '', -- ok | failed
  input        TEXT NOT NULL DEFAULT '{}',
  output       TEXT NOT NULL DEFAULT '{}',
  error        TEXT NOT NULL DEFAULT '',
  started_at   TIMESTAMPTZ NOT NULL,
  ended_at     TIMESTAMPTZ,
  duration_ms  BIGINT NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_execution_step_plan ON execution_step(plan_step_id);
CREATE INDEX IF NOT EXISTS idx_execution_step_plan_id ON execution_step(plan_id, idx);
CREATE INDEX IF NOT EXISTS idx_execution_step_task ON execution_step(task_id, cycle);

CREATE TABLE IF NOT EXISTS execution_step_interaction (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_id        BIGINT NOT NULL, -- execution_step.id
  seq            INTEGER NOT NULL, -- which interaction of that step (1-based)
  kind           TEXT NOT NULL DEFAULT '', -- llm | http | local
  provider       TEXT NOT NULL DEFAULT '',
  reason_turn_id BIGINT, -- reason_turns.id for an LLM interaction
  created_at     TIMESTAMPTZ NOT NULL,
  UNIQUE(step_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_execution_step_interaction_step ON execution_step_interaction(step_id);
CREATE INDEX IF NOT EXISTS idx_execution_step_interaction_turn ON execution_step_interaction(reason_turn_id);
`

// CreateExecutionPlan writes one plan. This is the only statement that ever touches the
// row: a plan is one-shot, and a re-plan is a new plan.
func (s *PostgresStore) CreateExecutionPlan(plan ExecutionPlan) (int64, error) {
	if strings.TrimSpace(plan.TaskID) == "" {
		return 0, fmt.Errorf("create execution plan: missing task id")
	}
	var id int64
	err := s.db.QueryRow(`
INSERT INTO execution_plan
  (task_id, agent_id, cycle, decision_type, reason, evidence, need, step_count, plan_hash,
   reply_message_id, input_message_id, task_input_message_id, reason_turn_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`,
		plan.TaskID, plan.AgentID, plan.Cycle, plan.DecisionType, plan.Reason,
		orJSONArray(plan.Evidence), orJSONObject(plan.Need), plan.StepCount, plan.PlanHash,
		nullID(plan.ReplyMessageID), nullID(plan.InputMessageID),
		nullID(plan.TaskInputMessageID), nullID(plan.ReasonTurnID),
		pgTime(plan.CreatedAt)).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("create execution plan: %w", err)
	}
	return id, nil
}

// AppendExecutionStepPlans writes a plan's steps in one transaction: a plan is either
// written in full before its first step runs, or not at all.
func (s *PostgresStore) AppendExecutionStepPlans(steps []ExecutionStepPlan) error {
	if len(steps) == 0 {
		return nil
	}
	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("begin execution step plan tx: %w", err)
	}
	stmt, err := tx.Prepare(`
INSERT INTO execution_step_plan (plan_id, idx, name, capability, input, expected_effect, evidence_refs, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`)
	if err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("prepare execution step plan insert: %w", err)
	}
	defer stmt.Close()
	for _, step := range steps {
		if _, err := stmt.Exec(step.PlanID, step.Idx, step.Name, step.Capability, orJSONObject(step.Input),
			step.ExpectedEffect, orJSONArray(step.EvidenceRefs), pgTime(step.CreatedAt)); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("append execution step plan: %w", err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit execution step plan: %w", err)
	}
	return nil
}

// AppendExecutionStep records one step that ran, linked to the planned step it carries
// out by id, so a re-plan's identical step can never be confused with it.
func (s *PostgresStore) AppendExecutionStep(step ExecutionStep) (int64, error) {
	var id int64
	err := s.db.QueryRow(`
INSERT INTO execution_step
  (plan_id, plan_step_id, task_id, agent_id, cycle, idx, name, capability, provider, status,
   input, output, error, started_at, ended_at, duration_ms, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id
`,
		step.PlanID, step.PlanStepID, step.TaskID, step.AgentID, step.Cycle, step.Idx,
		step.Name, step.Capability, step.Provider, step.Status,
		orJSONObject(step.Input), orJSONObject(step.Output), step.Error,
		pgTime(step.StartedAt), pgNullTime(step.EndedAt), step.DurationMS, pgTime(step.CreatedAt)).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("append execution step: %w", err)
	}
	return id, nil
}

// AppendExecutionStepInteraction records one provider interaction of one step.
func (s *PostgresStore) AppendExecutionStepInteraction(in ExecutionStepInteraction) (int64, error) {
	var id int64
	err := s.db.QueryRow(`
INSERT INTO execution_step_interaction (step_id, seq, kind, provider, reason_turn_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`,
		in.StepID, in.Seq, in.Kind, in.Provider, nullID(in.ReasonTurnID), pgTime(in.CreatedAt)).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("append execution step interaction: %w", err)
	}
	return id, nil
}

// AssistantMessageID is the row a run's reply was recorded in. The reply is the run's
// last message, so it is read back by role rather than assumed by seq (a run whose
// stream ended mid-flight still has its return as the assistant row).
func (s *PostgresStore) AssistantMessageID(turnID int64) (int64, bool, error) {
	var id int64
	err := s.db.QueryRow(`
SELECT id FROM llm_messages
 WHERE turn_id = $1 AND role = $2 ORDER BY seq DESC LIMIT 1`,
		turnID, string(LLMMessageRoleAssistant)).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, fmt.Errorf("read assistant message: %w", err)
	}
	return id, true, nil
}

// TaskInputMessageID is the task's own first user input, as recorded on its first
// plan. Every plan of a task points at it, so "which input asked for this" is one hop
// from any plan of any cycle.
func (s *PostgresStore) TaskInputMessageID(taskID string) (int64, bool, error) {
	var id int64
	err := s.db.QueryRow(`
SELECT task_input_message_id FROM execution_plan
 WHERE task_id = $1 AND task_input_message_id IS NOT NULL
 ORDER BY id LIMIT 1`, taskID).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, fmt.Errorf("read task input message: %w", err)
	}
	return id, true, nil
}

// ListExecutionPlans reads a task's plans in creation order, oldest first.
func (s *PostgresStore) ListExecutionPlans(taskID string) ([]ExecutionPlan, error) {
	rows, err := s.db.Query(`
SELECT id, task_id, agent_id, cycle, decision_type, reason, evidence, need, step_count,
       plan_hash, reply_message_id, input_message_id, task_input_message_id, reason_turn_id, created_at
  FROM execution_plan WHERE task_id = $1 ORDER BY id`, taskID)
	if err != nil {
		return nil, fmt.Errorf("list execution plans: %w", err)
	}
	defer rows.Close()
	out := []ExecutionPlan{}
	for rows.Next() {
		var (
			plan                            ExecutionPlan
			reply, input, taskInput, turnID sql.NullInt64
			createdAt                       time.Time
		)
		if err := rows.Scan(&plan.ID, &plan.TaskID, &plan.AgentID, &plan.Cycle, &plan.DecisionType,
			&plan.Reason, &plan.Evidence, &plan.Need, &plan.StepCount, &plan.PlanHash,
			&reply, &input, &taskInput, &turnID, &createdAt); err != nil {
			return nil, fmt.Errorf("scan execution plan: %w", err)
		}
		plan.ReplyMessageID = reply.Int64
		plan.InputMessageID = input.Int64
		plan.TaskInputMessageID = taskInput.Int64
		plan.ReasonTurnID = turnID.Int64
		plan.CreatedAt = createdAt.UTC()
		out = append(out, plan)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list execution plans: %w", err)
	}
	return out, nil
}

// ListExecutionStepPlan reads a plan's planned steps in plan order.
func (s *PostgresStore) ListExecutionStepPlan(planID int64) ([]ExecutionStepPlan, error) {
	rows, err := s.db.Query(`
SELECT id, plan_id, idx, name, capability, input, expected_effect, evidence_refs, created_at
  FROM execution_step_plan WHERE plan_id = $1 ORDER BY idx`, planID)
	if err != nil {
		return nil, fmt.Errorf("list execution step plan: %w", err)
	}
	defer rows.Close()
	out := []ExecutionStepPlan{}
	for rows.Next() {
		var step ExecutionStepPlan
		var createdAt time.Time
		if err := rows.Scan(&step.ID, &step.PlanID, &step.Idx, &step.Name, &step.Capability, &step.Input,
			&step.ExpectedEffect, &step.EvidenceRefs, &createdAt); err != nil {
			return nil, fmt.Errorf("scan execution step plan: %w", err)
		}
		step.CreatedAt = createdAt.UTC()
		out = append(out, step)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list execution step plan: %w", err)
	}
	return out, nil
}

// ListExecutionSteps reads a plan's executed steps in execution order.
func (s *PostgresStore) ListExecutionSteps(planID int64) ([]ExecutionStep, error) {
	rows, err := s.db.Query(`
SELECT id, plan_id, plan_step_id, task_id, agent_id, cycle, idx, name, capability, provider, status,
       input, output, error, started_at, ended_at, duration_ms, created_at
  FROM execution_step WHERE plan_id = $1 ORDER BY idx, id`, planID)
	if err != nil {
		return nil, fmt.Errorf("list execution steps: %w", err)
	}
	defer rows.Close()
	out := []ExecutionStep{}
	for rows.Next() {
		var (
			step      ExecutionStep
			startedAt time.Time
			endedAt   sql.NullTime
			createdAt time.Time
		)
		if err := rows.Scan(&step.ID, &step.PlanID, &step.PlanStepID, &step.TaskID, &step.AgentID,
			&step.Cycle, &step.Idx, &step.Name, &step.Capability, &step.Provider, &step.Status,
			&step.Input, &step.Output, &step.Error, &startedAt, &endedAt, &step.DurationMS,
			&createdAt); err != nil {
			return nil, fmt.Errorf("scan execution step: %w", err)
		}
		step.StartedAt = startedAt.UTC()
		step.EndedAt = pgScanTime(endedAt)
		step.CreatedAt = createdAt.UTC()
		out = append(out, step)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list execution steps: %w", err)
	}
	return out, nil
}

// ListExecutionStepInteractions reads one step's interactions in Seq order.
func (s *PostgresStore) ListExecutionStepInteractions(stepID int64) ([]ExecutionStepInteraction, error) {
	rows, err := s.db.Query(`
SELECT id, step_id, seq, kind, provider, reason_turn_id, created_at
  FROM execution_step_interaction WHERE step_id = $1 ORDER BY seq`, stepID)
	if err != nil {
		return nil, fmt.Errorf("list execution step interactions: %w", err)
	}
	defer rows.Close()
	out := []ExecutionStepInteraction{}
	for rows.Next() {
		var (
			in        ExecutionStepInteraction
			turnID    sql.NullInt64
			createdAt time.Time
		)
		if err := rows.Scan(&in.ID, &in.StepID, &in.Seq, &in.Kind, &in.Provider, &turnID, &createdAt); err != nil {
			return nil, fmt.Errorf("scan execution step interaction: %w", err)
		}
		in.ReasonTurnID = turnID.Int64
		in.CreatedAt = createdAt.UTC()
		out = append(out, in)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list execution step interactions: %w", err)
	}
	return out, nil
}

// ExecutionPlanOutcome derives a plan's result from its steps: how much of the plan ran
// and how the last step of it ended. A plan whose steps never ran has no outcome — its
// planned steps are still there, which is the whole record of it.
func (s *PostgresStore) ExecutionPlanOutcome(planID int64) (ExecutionPlanOutcome, bool, error) {
	out := ExecutionPlanOutcome{PlanID: planID}
	if err := s.db.QueryRow(`SELECT count(*) FROM execution_step_plan WHERE plan_id = $1`, planID).
		Scan(&out.Planned); err != nil {
		return out, false, fmt.Errorf("count planned steps: %w", err)
	}
	if err := s.db.QueryRow(`SELECT count(*) FROM execution_step WHERE plan_id = $1`, planID).
		Scan(&out.Executed); err != nil {
		return out, false, fmt.Errorf("count executed steps: %w", err)
	}
	err := s.db.QueryRow(`
SELECT id, status, error FROM execution_step
 WHERE plan_id = $1 ORDER BY idx DESC, id DESC LIMIT 1`, planID).
		Scan(&out.StepID, &out.Status, &out.Error)
	if errors.Is(err, sql.ErrNoRows) {
		return out, false, nil
	}
	if err != nil {
		return out, false, fmt.Errorf("read last execution step: %w", err)
	}
	return out, true, nil
}
