package db

import . "github.com/kaulie/autonomy/src"

import (
	"fmt"
	"strings"
	"time"
)

// VerificationStore, as the postgres engine serves it: a task's pinned Completion
// Contract (written once) and its verdicts (appended, never updated). See
// docs/verification.md.

// pgVerificationDDL creates the contract and the verdict log.
const pgVerificationDDL = `
-- completion_contract is the contract a task is judged by: the facts that must hold for
-- it to be done. It is written once, by the run's first answer, and never rewritten --
-- a (task_id, idx) that is already there keeps its criterion, which is what makes the
-- standard a done cannot weaken on the way out.
CREATE TABLE IF NOT EXISTS completion_contract (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id    TEXT NOT NULL DEFAULT '',
  idx        INTEGER NOT NULL DEFAULT 0, -- position in the contract (1-based)
  plan_id    BIGINT NOT NULL DEFAULT 0,  -- the plan it arrived with (execution_plan.id)
  name       TEXT NOT NULL DEFAULT '',   -- what the criterion is called
  criterion  TEXT NOT NULL DEFAULT '{}', -- the criterion's JSON, verbatim
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE(task_id, idx)
);
CREATE INDEX IF NOT EXISTS idx_completion_contract_task ON completion_contract(task_id, idx);

-- verification is one verdict on one criterion: what the contract said must hold, what
-- the authoritative source answered, and where that answer came from. Appended, never
-- updated.
CREATE TABLE IF NOT EXISTS verification (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id      TEXT NOT NULL DEFAULT '',
  plan_id      BIGINT NOT NULL DEFAULT 0,
  cycle        INTEGER NOT NULL DEFAULT 0,
  criterion    TEXT NOT NULL DEFAULT '',
  requirement  TEXT NOT NULL DEFAULT '',
  method       TEXT NOT NULL DEFAULT '', -- world_model | registry:<cap> | declared:<cap> | -
  evidence     TEXT NOT NULL DEFAULT '{}', -- {"slot": "…", "reference": "…"}
  expected     TEXT NOT NULL DEFAULT '',
  observed     TEXT NOT NULL DEFAULT '',
  result       TEXT NOT NULL DEFAULT '', -- pass | fail | inconclusive
  reason       TEXT NOT NULL DEFAULT '',
  created_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_verification_task ON verification(task_id, id);
CREATE INDEX IF NOT EXISTS idx_verification_plan ON verification(plan_id);
`

// AppendCompletionContract pins one criterion. The first row for a (task_id, idx) is the
// one kept: ON CONFLICT DO NOTHING is what makes "the contract cannot be rewritten" a
// fact of the schema rather than a check somebody has to remember to make.
func (s *PostgresStore) AppendCompletionContract(criterion ContractCriterion) error {
	if strings.TrimSpace(criterion.TaskID) == "" {
		return fmt.Errorf("append completion contract: missing task id")
	}
	if _, err := s.db.Exec(`
INSERT INTO completion_contract (task_id, idx, plan_id, name, criterion, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (task_id, idx) DO NOTHING`,
		criterion.TaskID, criterion.Idx, criterion.PlanID, criterion.Name,
		orJSONObjectText(criterion.Criterion), pgTime(criterion.CreatedAt)); err != nil {
		return fmt.Errorf("append completion contract: %w", err)
	}
	return nil
}

// ListCompletionContract reads a task's pinned contract in criterion order.
func (s *PostgresStore) ListCompletionContract(taskID string) ([]ContractCriterion, error) {
	rows, err := s.db.Query(`
SELECT id, task_id, idx, plan_id, name, criterion, created_at
FROM completion_contract WHERE task_id = $1 ORDER BY idx`, taskID)
	if err != nil {
		return nil, fmt.Errorf("list completion contract: %w", err)
	}
	defer rows.Close()
	out := []ContractCriterion{}
	for rows.Next() {
		var (
			id      int64
			row     ContractCriterion
			created time.Time
		)
		if err := rows.Scan(&id, &row.TaskID, &row.Idx, &row.PlanID, &row.Name, &row.Criterion, &created); err != nil {
			return nil, fmt.Errorf("scan completion contract: %w", err)
		}
		row.CreatedAt = created.UTC()
		out = append(out, row)
	}
	return out, rows.Err()
}

// AppendVerification records one verdict. A verdict is never rewritten: the question
// "what did the runtime believe at cycle 3" has one answer.
func (s *PostgresStore) AppendVerification(v Verification) (int64, error) {
	var id int64
	err := s.db.QueryRow(`
INSERT INTO verification
  (task_id, plan_id, cycle, criterion, requirement, method, evidence, expected, observed, result, reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id`,
		v.TaskID, v.PlanID, v.Cycle, v.Criterion, v.Requirement, v.Method,
		orJSONObjectText(v.Evidence), v.Expected, v.Observed, v.Result, v.Reason, pgTime(v.CreatedAt)).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("append verification: %w", err)
	}
	return id, nil
}

// ListVerifications reads a task's verdicts in creation order, oldest first.
func (s *PostgresStore) ListVerifications(taskID string) ([]Verification, error) {
	rows, err := s.db.Query(`
SELECT id, task_id, plan_id, cycle, criterion, requirement, method, evidence,
       expected, observed, result, reason, created_at
FROM verification WHERE task_id = $1 ORDER BY id`, taskID)
	if err != nil {
		return nil, fmt.Errorf("list verifications: %w", err)
	}
	defer rows.Close()
	out := []Verification{}
	for rows.Next() {
		var (
			row     Verification
			created time.Time
		)
		if err := rows.Scan(&row.ID, &row.TaskID, &row.PlanID, &row.Cycle, &row.Criterion,
			&row.Requirement, &row.Method, &row.Evidence, &row.Expected, &row.Observed,
			&row.Result, &row.Reason, &created); err != nil {
			return nil, fmt.Errorf("scan verification: %w", err)
		}
		row.CreatedAt = created.UTC()
		out = append(out, row)
	}
	return out, rows.Err()
}
