package db

import . "github.com/kaulie/autonomy/src"

import (
	"database/sql"
	"fmt"
	"time"
)

// InboxStore, as the postgres engine serves it: one row per message per agent.
//
// The queue order is the row id, so "the next message" is the oldest queued row for that
// agent — no separate sequence, no clock to trust. Claiming it is one guarded UPDATE,
// so two consumers can never take the same message: the second one finds the row is no
// longer queued and takes nothing. It is a single statement (unlike the sqlite engine's
// select-then-update) because PostgreSQL can return the claimed row: RETURNING hands
// back exactly the row this statement just marked running.

// pgInboxDDL creates the inbox table and the indexes the queue reads it with.
const pgInboxDDL = `
CREATE TABLE IF NOT EXISTS agent_messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id   BIGINT NOT NULL,
  task_id    TEXT NOT NULL DEFAULT '',
  sender     TEXT NOT NULL DEFAULT '',
  sender_id  TEXT NOT NULL DEFAULT '',
  kind       TEXT NOT NULL DEFAULT '',
  content    TEXT NOT NULL DEFAULT '',
  status     TEXT NOT NULL DEFAULT 'queued',
  error      TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  started_at TIMESTAMPTZ,
  ended_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_agent_messages_queue ON agent_messages(agent_id, status, id);
CREATE INDEX IF NOT EXISTS idx_agent_messages_task ON agent_messages(task_id, id);
`

// pgAgentMessageColumns is every column one message row carries, in the order
// pgScanAgentMessage fills them.
const pgAgentMessageColumns = `id, agent_id, task_id, sender, sender_id, kind, content, status, error, created_at, started_at, ended_at`

// EnqueueMessage appends one message to an agent's inbox and returns its id, which is
// its place in the queue.
func (s *PostgresStore) EnqueueMessage(msg AgentMessage) (int64, error) {
	if msg.AgentID == 0 {
		return 0, fmt.Errorf("enqueue message: no agent")
	}
	status := msg.Status
	if status == "" {
		status = MessageStatusQueued
	}
	var id int64
	err := s.db.QueryRow(`
INSERT INTO agent_messages (agent_id, task_id, sender, sender_id, kind, content, status, error, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, '', $8)
RETURNING id
`, msg.AgentID, msg.TaskID, string(msg.Sender), msg.SenderID, string(msg.Kind), msg.Content,
		string(status), pgTime(msg.CreatedAt)).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("enqueue message: %w", err)
	}
	return id, nil
}

// ClaimNextMessage takes the oldest queued message for one agent and marks it running.
// found is false when the inbox is empty, and also when another consumer won the race
// for that message (the caller asks again — the queue is what it is).
func (s *PostgresStore) ClaimNextMessage(agentID int64) (AgentMessage, bool, error) {
	if agentID == 0 {
		return AgentMessage{}, false, nil
	}
	// The inner SELECT picks the queue head; the outer UPDATE only touches it if it is
	// still queued (a consumer that lost the race updates nothing and finds nothing).
	row := s.db.QueryRow(`
UPDATE agent_messages SET status = $2, started_at = $3
WHERE id = (SELECT id FROM agent_messages WHERE agent_id = $1 AND status = $4 ORDER BY id LIMIT 1)
  AND status = $4
RETURNING `+pgAgentMessageColumns,
		agentID, string(MessageStatusRunning), pgTime(time.Now()), string(MessageStatusQueued))
	msg, err := pgScanAgentMessage(row)
	if err == sql.ErrNoRows {
		return AgentMessage{}, false, nil
	}
	if err != nil {
		return AgentMessage{}, false, fmt.Errorf("claim message of agent %d: %w", agentID, err)
	}
	return msg, true, nil
}

// pgScanAgentMessage reads one message row: the columns pgAgentMessageColumns selects.
func pgScanAgentMessage(row interface{ Scan(dest ...any) error }) (AgentMessage, error) {
	var (
		msg              AgentMessage
		sender, senderID string
		kind, status     string
		created          time.Time
		started, ended   sql.NullTime
	)
	err := row.Scan(&msg.ID, &msg.AgentID, &msg.TaskID, &sender, &senderID, &kind, &msg.Content, &status,
		&msg.Error, &created, &started, &ended)
	if err != nil {
		return AgentMessage{}, err
	}
	msg.Sender = MessageSender(sender)
	msg.SenderID = senderID
	msg.Kind = AgentMessageKind(kind)
	msg.Status = AgentMessageStatus(status)
	msg.CreatedAt = created.UTC()
	msg.StartedAt = pgScanTime(started)
	msg.EndedAt = pgScanTime(ended)
	return msg, nil
}

// agentMessage reads one row back as the message the queue works with.
func (s *PostgresStore) agentMessage(id int64) (AgentMessage, error) {
	msg, err := pgScanAgentMessage(s.db.QueryRow(`
SELECT `+pgAgentMessageColumns+` FROM agent_messages WHERE id = $1
`, id))
	if err != nil {
		return AgentMessage{}, fmt.Errorf("read message %d: %w", id, err)
	}
	return msg, nil
}

// FinishAgentMessage records how one message ended.
func (s *PostgresStore) FinishAgentMessage(id int64, status AgentMessageStatus, errText string) error {
	if status == "" {
		status = MessageStatusDone
	}
	if _, err := s.db.Exec(`
UPDATE agent_messages SET status = $1, error = $2, ended_at = $3 WHERE id = $4
`, string(status), errText, pgTime(time.Now()), id); err != nil {
		return fmt.Errorf("finish message %d: %w", id, err)
	}
	return nil
}

// RequeueRunningMessages puts an agent's running messages back in the queue: a message
// a process claimed and then died on is still the agent's to process.
func (s *PostgresStore) RequeueRunningMessages(agentID int64) error {
	if agentID == 0 {
		return nil
	}
	if _, err := s.db.Exec(`
UPDATE agent_messages SET status = $1, started_at = NULL WHERE agent_id = $2 AND status = $3
`, string(MessageStatusQueued), agentID, string(MessageStatusRunning)); err != nil {
		return fmt.Errorf("requeue messages of agent %d: %w", agentID, err)
	}
	return nil
}

// RequeueMessage puts one claimed message back in the queue, where it was: a run that
// must not start yet (a graceful restart is draining, src/graceful.go) is left for the
// consumer that starts next. Only the row that is running goes back — the id is the
// message's place in the queue, so it is claimed again before anything behind it.
func (s *PostgresStore) RequeueMessage(id int64) error {
	if id == 0 {
		return nil
	}
	if _, err := s.db.Exec(`
UPDATE agent_messages SET status = $1, started_at = NULL WHERE id = $2 AND status = $3
`, string(MessageStatusQueued), id, string(MessageStatusRunning)); err != nil {
		return fmt.Errorf("requeue message %d: %w", id, err)
	}
	return nil
}

// CountQueuedMessages counts the messages waiting for one agent — what the drain asks
// to know whether the message it just finished was the last one.
//
// It is a read, but never a follower read: the drain decides whether to keep the
// consumer alive on this answer, and a follower still catching up would answer "dry"
// for a message this process has already queued. The inbox is control data, so it
// reads through the writer (docs/store.md「读写分离」).
func (s *PostgresStore) CountQueuedMessages(agentID int64) (int, error) {
	if agentID == 0 {
		return 0, nil
	}
	var n int
	if err := s.db.QueryRow(`
SELECT count(*) FROM agent_messages WHERE agent_id = $1 AND status = $2
`, agentID, string(MessageStatusQueued)).Scan(&n); err != nil {
		return 0, fmt.Errorf("count queued messages of agent %d: %w", agentID, err)
	}
	return n, nil
}

// CountMessagesAhead counts the messages an agent still has in front of one message:
// the ones that arrived before it and have not finished (queued, or being processed
// right now). The queue's order is the row id, so "before it" is `id <`.
//
// Like CountQueuedMessages it reads through the writer: the message it counts from is
// one this process has just enqueued, so an answer from a follower could report a
// queue that is shorter than the one the caller can already see.
func (s *PostgresStore) CountMessagesAhead(agentID, messageID int64) (int, error) {
	if agentID == 0 || messageID == 0 {
		return 0, nil
	}
	var n int
	if err := s.db.QueryRow(`
SELECT count(*) FROM agent_messages
WHERE agent_id = $1 AND id < $2 AND status IN ($3, $4)
`, agentID, messageID, string(MessageStatusQueued), string(MessageStatusRunning)).Scan(&n); err != nil {
		return 0, fmt.Errorf("count messages ahead of %d for agent %d: %w", messageID, agentID, err)
	}
	return n, nil
}

// ListAgentMessages reads an agent's inbox in arrival order. limit <= 0 means all of it.
func (s *PostgresStore) ListAgentMessages(agentID int64, limit int) ([]AgentMessage, error) {
	if agentID == 0 {
		return nil, nil
	}
	query := `SELECT ` + pgAgentMessageColumns + ` FROM agent_messages WHERE agent_id = $1 ORDER BY id`
	args := []any{agentID}
	if limit > 0 {
		query += ` LIMIT $2`
		args = append(args, limit)
	}
	rows, err := s.readPool().Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("list messages of agent %d: %w", agentID, err)
	}
	defer rows.Close()
	var out []AgentMessage
	for rows.Next() {
		msg, err := pgScanAgentMessage(rows)
		if err != nil {
			return nil, fmt.Errorf("list messages of agent %d: %w", agentID, err)
		}
		out = append(out, msg)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list messages of agent %d: %w", agentID, err)
	}
	return out, nil
}
